"""Convert the official OCHA 2024 vertical logo (UN emblem + OCHA) into a compact
JS module the card engine can draw as vectors.

The business card does NOT use the spelled-out logo files: as in the 2025 .ai
masters, it sets the vertical logo and typesets the name of the office below it
(larger than in the spelled-out logo, so it stays legible at card size). That
text lives in src/card.js (DESCRIPTOR).

Source of truth: the 2024 master set in the BDU Dropbox. The SVGs there are pure
single-colour path/polygon art with no transforms (verified 2026-09-21); this
script refuses to run if that stops being true, because silently dropping a
transform or a second colour would ship a distorted logo on every card.

Run from the repo root:  python3 scripts/build_logos.py
"""
import json
import os
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.svgLib.path import parse_path

LOGO_REL = "Design/Logos/ocha_logo/2024/OCHA_logo_2024/2_Web_RGB/main/OCHA_logo_vertical_blue.svg"
OUT = Path(__file__).resolve().parent.parent / "src" / "logos.js"
NS = "{http://www.w3.org/2000/svg}"


def fmt(v):
    return f"{v:.3f}".rstrip("0").rstrip(".")


def convert(path: Path):
    text = path.read_text(encoding="utf-8")
    if "transform" in text:
        sys.exit(f"{path.name}: contains a transform — update build_logos.py to apply it")
    fills = set(re.findall(r"fill:\s*(#[0-9a-fA-F]{3,6})", text))
    if fills != {"#009edb"}:
        sys.exit(f"{path.name}: expected only #009edb fill, found {fills}")
    root = ET.fromstring(text)
    vb = [float(x) for x in root.get("viewBox").split()]
    # One path string PER ELEMENT. Never merge them: under the nonzero fill rule,
    # overlapping shapes with opposite winding cancel out — merged, the continents
    # on the UN globe rendered inverted (found 2026-09-21).
    paths = []
    for el in root.iter():
        tag = el.tag.replace(NS, "")
        pen = SVGPathPen(None, ntos=fmt)
        if tag == "path":
            parse_path(el.get("d"), pen)
        elif tag in ("polygon", "polyline"):
            nums = [float(n) for n in re.split(r"[\s,]+", el.get("points").strip()) if n]
            pts = list(zip(nums[::2], nums[1::2]))
            pen.moveTo(pts[0])
            for p in pts[1:]:
                pen.lineTo(p)
            pen.closePath()
        elif tag in ("rect", "circle", "ellipse", "line", "use", "image", "text"):
            sys.exit(f"{path.name}: unsupported <{tag}> — extend build_logos.py")
        if pen.getCommands():
            paths.append(pen.getCommands())
    return {"w": vb[2], "h": vb[3], "paths": paths}


def find_logo() -> Path:
    """The master set lives in the OCHA DMU team Dropbox. The folder above
    `Design/` differs per person, so search every top-level folder; OCHA_LOGO_SVG
    overrides the search if the file is somewhere else."""
    override = os.environ.get("OCHA_LOGO_SVG")
    if override:
        return Path(override).expanduser()
    hits = sorted((Path.home() / "OCHA DMU Dropbox").glob(f"*/{LOGO_REL}"))
    if not hits:
        sys.exit(f"Logo master not found under ~/OCHA DMU Dropbox/*/{LOGO_REL}\n"
                 "Set OCHA_LOGO_SVG=/path/to/OCHA_logo_vertical_blue.svg and run again.")
    return hits[0]


def main():
    logo = convert(find_logo())
    OUT.write_text(
        "// GENERATED by scripts/build_logos.py from the OCHA 2024 logo master set. Do not edit.\n"
        "// Vertical OCHA logo (emblem + OCHA). One path per shape, SVG units (y down).\n"
        f"export const LOGO = {json.dumps(logo, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
